#索引库
#source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'

target 'LGAfterschoolPlanFramework_Example' do
  pod 'LGAfterschoolPlan', :path => '../'

pod 'AFNetworking', '3.2.1'
  
end
